### ISSUE TITLE
Wir haben geeignete Bibliotheken gefunden

### ISSUE THREAD

**Issue by Frank-Mayer** [Frank-Mayer/inno-lab#9]
Bei Web APIs auf Datenschutz achten!

**Comment by Frank-Mayer** [comment]
https://github.com/iperov/DeepFaceLab

**Comment by Frank-Mayer** [comment]
https://ollama.ai/

**Comment by Frank-Mayer** [comment]
https://docs.midjourney.com/docs/permutations

Keine Midjourney API. Discord API?

**Comment by Frank-Mayer** [comment]
https://docs.midjourney.com/docs/privacy-policy

**Comment by blackstardust** [comment]
Anfrage an Midjourney ob wir Bilder auf Anfrage löschen können.
